ignored:
  - DL3008  # pin versions in apt-get install — impractical for dev images
  - DL3028  # pin versions in gem install — impractical for dev images
  - DL3059  # multiple consecutive RUN instructions — intentional for clarity
